import { expect, test } from "@playwright/test";

test("login and logout", async ({ page }) => {
  test.setTimeout(180_000);
  const changedPassword = "DemoPass9A";
  const campaignName = `Ashenmoor ${Date.now()}`;
  const wizardCampaignName = `Wizard Ashenmoor ${Date.now()}`;
  const canceledWizardCampaignName = `Canceled Wizard ${Date.now()}`;
  const sourceSessionName = `${campaignName} Part 1`;
  const archivedSessionPattern = /Part 3 \(\d{4}-\d{2}-\d{2}\)$/;
  const pipelineSessionName = `${campaignName} Part 2`;
  const sessionName = `${campaignName} Part 3`;
  const wizardSessionName = `${wizardCampaignName} Part 1`;
  const templateName = `Arrival Beat ${Date.now()}`;
  const templateFilename = `${templateName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")}.md`;
  const sessionFilename = `${sessionName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "")}.md`;
  const imagePrompt = `A neon sigil in fog ${Date.now()}`;
  const adminUsername = `writer-${Date.now()}`;
  const adminPassword = "WriterPass9A";
  const customEndpointName = `OpenRouter ${Date.now()}`;
  const concurrentPromptA = `Concurrent stream alpha ${Date.now()} keeps running while another session becomes active.`;
  const concurrentPromptB = `Concurrent stream beta ${Date.now()} starts after switching sessions without canceling alpha.`;
  await page.goto("/terms");
  await expect(page.getByRole("heading", { name: "TracyHill RP Terms" })).toBeVisible();
  await expect(page.getByText("email-backed MFA, remembered devices, registration verification, forgot-password reset, and staged account deletion", { exact: false })).toBeVisible();
  await page.goto("/privacy");
  await expect(page.getByRole("heading", { name: "TracyHill RP Privacy" })).toBeVisible();
  await page.goto("/");
  await page.getByLabel("Username").fill("demo");
  await page.getByLabel("Password").fill("demo-pass");
  await page.getByRole("button", { name: "Log In" }).click();
  await expect(page.getByRole("heading", { name: "Workspace" })).toBeVisible();
  const optionsButton = page.getByRole("button", { name: "Options" });
  const openOptions = async () => {
    if ((await optionsButton.getAttribute("aria-expanded")) !== "true") await optionsButton.click();
  };
  await page.getByRole("button", { name: "Campaigns" }).click();
  const campaignsDialog = page.getByRole("dialog", { name: "Campaigns" });
  await expect(campaignsDialog).toBeVisible();
  await campaignsDialog.getByLabel("Wizard example state seed").fill("Reference seed structure");
  await campaignsDialog.getByLabel("Wizard example system prompt").fill("Reference system prompt structure");
  await campaignsDialog.getByLabel("Wizard seed update template").fill("Shared seed update template");
  await campaignsDialog.getByLabel("Wizard system prompt update template").fill("Shared system prompt update template");
  await campaignsDialog.getByRole("button", { name: "Save Wizard Templates" }).click();
  await campaignsDialog.getByRole("button", { name: "Close" }).click();
  await page.getByRole("button", { name: "New Campaign Wizard" }).click();
  if (await page.getByRole("button", { name: "Replace Wizard" }).isVisible().catch(() => false)) {
    await page.getByRole("button", { name: "Replace Wizard" }).click();
  }
  await expect(page.locator(".detail-head").getByRole("heading", { name: "Campaign Wizard" })).toBeVisible();
  await page.getByLabel("Message prompt").fill(`Call the campaign ${wizardCampaignName}. A grim city of ash, a haunted heir, and a court of dangerous allies define the setup.`);
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByRole("button", { name: "Generate Campaign" })).toBeEnabled({ timeout: 15000 });
  await page.getByRole("button", { name: "Generate Campaign" }).click();
  await expect(page.getByText(`Wizard review prepared for ${wizardCampaignName}`, { exact: false }).first()).toBeVisible();
  const wizardActivityCard = page.locator(".placeholder-card").filter({
    has: page.getByText(wizardCampaignName, { exact: true }),
    has: page.getByRole("button", { name: "Open Review" }),
  }).first();
  await wizardActivityCard.getByRole("button", { name: "Open Review" }).click();
  const wizardReviewDialog = page.getByRole("dialog", { name: "Wizard Review" });
  await expect(wizardReviewDialog).toBeVisible();
  await expect(wizardReviewDialog.getByLabel("Wizard review campaign name")).toHaveValue(wizardCampaignName);
  await wizardReviewDialog.getByRole("button", { name: "State Seed" }).click();
  await wizardReviewDialog.getByLabel("Wizard review State Seed").fill(`# ${wizardCampaignName} State Seed v0\n\nEdited in dedicated review.`);
  await wizardReviewDialog.getByRole("button", { name: "Approve & Start Campaign" }).click();
  const wizardSessionButton = page.getByRole("button", { name: new RegExp(`${escapeRegExp(wizardSessionName)}$`) }).first();
  await expect(wizardSessionButton).toBeVisible();
  await wizardSessionButton.click();
  await expect(page.getByRole("heading", { name: wizardSessionName })).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("Edited in dedicated review.", { exact: false }).first()).toBeVisible();
  await expect(page.locator(".wizard-slot-panel")).toContainText("empty");
  await page.getByRole("button", { name: "Campaigns" }).click();
  await expect(campaignsDialog).toBeVisible();
  await campaignsDialog.getByLabel("Wizard campaign name").fill(canceledWizardCampaignName);
  await campaignsDialog.getByLabel("Wizard model").selectOption({ label: "Gemini 2.5 Flash" });
  await campaignsDialog.getByLabel("Wizard campaign brief").fill("A second wizard run that should be canceled.");
  await campaignsDialog.getByLabel("Wizard transcript").fill("### User\n\nA second wizard run that should be canceled.\n");
  await campaignsDialog.getByRole("button", { name: "Run Wizard" }).click();
  await expect(page.getByRole("heading", { name: "Active Or Reviewable Wizard Runs" })).toBeVisible();
  await expect(page.getByText(canceledWizardCampaignName, { exact: true }).first()).toBeVisible();
  await campaignsDialog.getByRole("button", { name: "Close" }).click();
  await page.getByLabel("New folder name").fill(campaignName);
  await page.getByRole("button", { name: "Create" }).first().click();
  await page.getByRole("button", { name: "Campaigns" }).click();
  await expect(campaignsDialog).toBeVisible();
  await campaignsDialog.getByLabel("Campaign name", { exact: true }).fill(campaignName);
  await campaignsDialog.getByLabel("Campaign folder").selectOption({ label: campaignName });
  await campaignsDialog.getByLabel("Pipeline model").selectOption({ label: "Gemini 2.5 Flash" });
  await campaignsDialog.getByLabel("Campaign current version").fill("0");
  await campaignsDialog.getByLabel("Campaign seed update prompt").fill("Keep the state seed fully self-contained and transcript-grounded.");
  await campaignsDialog.getByLabel("Campaign system prompt update prompt").fill("Revise the system prompt only for durable continuity rules.");
  await campaignsDialog.getByLabel("Campaign system prompt", { exact: true }).fill("You are the chronicler of Ashenmoor.");
  await campaignsDialog.getByLabel("Campaign state seed").fill("The city waits under ash.");
  await campaignsDialog.getByRole("button", { name: "Create Campaign" }).click();
  const campaignCard = campaignsDialog.locator(`xpath=.//article[contains(@class,"placeholder-card")][.//strong[normalize-space()="${campaignName}"]]`);
  await expect(campaignCard).toContainText("Version 0");
  await campaignCard.getByRole("button", { name: "Edit" }).click();
  await campaignsDialog.getByLabel(`Edit system prompt ${campaignName}`).fill("You are the chronicler of Ashenmoor, revised.");
  await campaignsDialog.getByRole("button", { name: "Save", exact: true }).click();
  await expect(campaignCard).toContainText("Version 1");
  await campaignCard.getByRole("button", { name: "Show History" }).click();
  await expect(campaignCard.getByText("Version 1 (Current)")).toBeVisible();
  await campaignCard.getByRole("button", { name: "Restore Version 0" }).click();
  await expect(campaignCard.getByText("Version 2 (Current)")).toBeVisible();
  await expect(campaignCard.getByText(`Linked folder: ${campaignName}`)).toBeVisible();
  await expect(campaignCard.getByText("Pipeline model: Gemini 2.5 Flash")).toBeVisible();
  await expect(campaignCard.getByText("Keep the state seed fully self-contained", { exact: false })).toBeVisible();
  await campaignCard.getByRole("button", { name: "Start Session" }).click();
  await campaignsDialog.getByRole("button", { name: "Close" }).click();
  await expect(page.getByRole("heading", { name: sourceSessionName })).toBeVisible();
  await page.getByRole("button", { name: "Campaigns" }).click();
  await expect(campaignsDialog).toBeVisible();
  await campaignCard.getByRole("button", { name: "Run Pipeline" }).click();
  await expect(page.getByRole("heading", { name: "Active Or Reviewable Runs" })).toBeVisible();
  await expect(campaignCard.getByText(campaignName, { exact: true })).toBeVisible();
  await expect(campaignCard.getByText("Pipeline review prepared", { exact: false })).toBeVisible();
  await expect(page.getByRole("button", { name: archivedSessionPattern })).toBeVisible();
  await campaignCard.getByRole("button", { name: "Show Review" }).click();
  await expect(campaignCard.getByText("## Pipeline Update Draft", { exact: false })).toBeVisible();
  await expect(campaignCard.locator(".small-copy").filter({ hasText: /^VALIDATION: PASS$/ }).first()).toBeVisible();
  await expect(campaignCard.getByText(/System prompt changes applied\.|No system prompt changes needed\./)).toBeVisible();
  await campaignCard.getByRole("button", { name: "Approve + Start Session" }).click();
  await expect(campaignCard.getByText(/Version 3 · Updated/)).toBeVisible();
  await campaignsDialog.getByRole("button", { name: "Close" }).click();
  await expect(page.getByRole("heading", { name: pipelineSessionName })).toBeVisible();
  await page.getByRole("button", { name: "Campaigns" }).click();
  await campaignCard.getByRole("button", { name: "Re-run Validation" }).click();
  await campaignCard.getByRole("button", { name: "Start Session" }).click();
  await campaignsDialog.getByRole("button", { name: "Close" }).click();
  await expect(page.getByRole("heading", { name: sessionName })).toBeVisible();
  await expect(page.getByText("Campaign Context")).toBeVisible();
  await page.getByLabel(`Move session ${sessionName}`).selectOption({ label: campaignName });
  await page.getByLabel("Chat model").click();
  await page.getByRole("button", { name: "Anthropic" }).click();
  await page.getByRole("button", { name: "Claude Sonnet 4", exact: true }).click();
  await page.getByRole("button", { name: "Templates", exact: true }).click();
  await page.getByLabel("Prompt template name").fill(templateName);
  await page.getByLabel("Prompt template content").fill("Describe the carriage arrival with rain, torchlight, and visible tension.");
  await page.getByRole("button", { name: "Create Template" }).click();
  const templateCard = page.locator(".template-card").filter({ hasText: templateName }).first();
  await expect(templateCard).toBeVisible();
  await templateCard.getByRole("button", { name: "Use" }).click();
  await expect(page.locator(".composer").getByText(templateFilename)).toBeVisible();
  await page.locator('input[type="file"]').setInputFiles({
    name: "scene.png",
    mimeType: "image/png",
    buffer: Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+yF9sAAAAASUVORK5CYII=", "base64"),
  });
  await expect(page.locator(".composer").getByRole("img", { name: "scene.png" })).toBeVisible();
  await page.getByLabel("Message prompt").fill("Hello from Slice 3");
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(page.getByText("Echo: Hello from Slice 3")).toBeVisible();
  await expect(page.locator(".message-card.role-user").filter({ hasText: "Hello from Slice 3" }).first().getByText(templateFilename, { exact: true })).toBeVisible();
  await expect(page.locator(".message-list").getByRole("img", { name: "scene.png" })).toBeVisible();
  const sessionRow = page.locator(".session-card").filter({ has: page.getByRole("button", { name: new RegExp(sessionName) }) }).first();
  const pipelineSessionRow = page.locator(".session-card").filter({ has: page.getByRole("button", { name: new RegExp(pipelineSessionName) }) }).first();
  await page.getByLabel("Message prompt").fill(concurrentPromptA);
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(sessionRow.locator(".stream-indicator")).toBeVisible();
  await pipelineSessionRow.getByRole("button", { name: new RegExp(pipelineSessionName) }).click();
  await expect(page.getByRole("heading", { name: pipelineSessionName })).toBeVisible();
  await expect(sessionRow.locator(".stream-indicator")).toBeVisible();
  await page.getByLabel("Message prompt").fill(concurrentPromptB);
  await page.getByRole("button", { name: "Send", exact: true }).click();
  await expect(pipelineSessionRow.locator(".stream-indicator")).toBeVisible();
  await sessionRow.getByRole("button", { name: new RegExp(sessionName) }).click();
  await expect(page.getByRole("heading", { name: sessionName })).toBeVisible();
  await expect(page.getByText(`Echo: ${concurrentPromptA}`)).toBeVisible();
  await pipelineSessionRow.getByRole("button", { name: new RegExp(pipelineSessionName) }).click();
  await expect(page.getByRole("heading", { name: pipelineSessionName })).toBeVisible();
  await expect(page.getByText(`Echo: ${concurrentPromptB}`)).toBeVisible();
  await sessionRow.getByRole("button", { name: new RegExp(sessionName) }).click();
  await expect(page.getByRole("heading", { name: sessionName })).toBeVisible();
  const userMessageCard = page.locator(".message-card.role-user").filter({ hasText: "Hello from Slice 3" }).first();
  await userMessageCard.getByRole("button", { name: "Edit" }).click();
  await page.getByLabel("Edit message").fill("Hello from Slice 3 revised");
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page.getByText("Hello from Slice 3 revised")).toBeVisible();
  await page.locator(".message-card.role-user").first().getByRole("button", { name: "Resend" }).click();
  await expect(page.getByText("Echo: Hello from Slice 3 revised")).toBeVisible();
  await page.keyboard.press("Control+f");
  await expect(page.getByLabel("Search current session")).toBeVisible();
  await page.getByLabel("Search current session").fill("Slice 3");
  await expect(page.getByText("1 / 2 matches")).toBeVisible();
  await expect(page.locator(".message-card.search-hit")).toHaveCount(2);
  await page.getByRole("button", { name: "Close" }).click();
  await page.getByLabel("Search workspace").fill("Slice 3");
  await expect(page.getByText('Results for "Slice 3"')).toBeVisible();
  await expect(page.locator(".search-results .search-result-card").first()).toBeVisible();
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export Markdown" }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe(sessionFilename);
  await page.locator(".session-card", { has: page.getByRole("button", { name: new RegExp(sessionName) }) }).first().getByRole("button", { name: "Delete" }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Delete" }).click();
  await expect(page.getByRole("heading", { name: "Recycle Bin" })).toBeVisible();
  await expect(page.locator(".recycle-bin-card").getByText(sessionName)).toBeVisible();
  await page.locator(".recycle-bin-card").getByRole("button", { name: "Restore" }).first().click();
  await page.locator(".session-card", { has: page.getByRole("button", { name: new RegExp(sessionName) }) }).first().getByRole("button", { name: new RegExp(sessionName) }).click();
  await expect(page.getByRole("heading", { name: sessionName })).toBeVisible();
  await page.locator(".session-card", { has: page.getByRole("button", { name: new RegExp(sessionName) }) }).first().getByRole("button", { name: "Delete" }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Delete" }).click();
  await page.getByRole("button", { name: "Empty Bin" }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Empty Bin" }).click();
  await expect(page.getByText("No deleted sessions.")).toBeVisible();
  await page.getByLabel("Image model").selectOption({ label: "GLM Image" });
  await page.getByLabel("Message prompt").fill(imagePrompt);
  await page.getByRole("button", { name: "Generate Image" }).click();
  await expect(page.getByRole("img", { name: imagePrompt })).toBeVisible();
  await openOptions();
  await page.getByRole("button", { name: "Users" }).click();
  const usersDialog = page.getByRole("dialog", { name: "Users" });
  await expect(usersDialog).toBeVisible();
  await usersDialog.getByRole("button", { name: "New User" }).click();
  await usersDialog.getByLabel("Admin create username").fill(adminUsername);
  await usersDialog.getByLabel("Admin create password").fill(adminPassword);
  await usersDialog.getByLabel("Admin create role").selectOption("user");
  await usersDialog.getByRole("button", { name: "Create User" }).click();
  await expect(usersDialog.getByText(adminUsername, { exact: true })).toBeVisible();
  await usersDialog.getByRole("button", { name: "Close" }).first().click();
  await openOptions();
  await page.getByRole("button", { name: "Storage" }).click();
  const storageDialog = page.getByRole("dialog", { name: "Storage" });
  await expect(storageDialog).toBeVisible();
  await expect(storageDialog.getByText("1 files", { exact: false })).toBeVisible();
  await storageDialog.getByRole("button", { name: "Purge Images" }).click();
  await storageDialog.getByRole("button", { name: "Confirm Purge Images" }).click();
  await expect(storageDialog.getByText("0 files", { exact: false })).toBeVisible();
  await storageDialog.getByRole("button", { name: "Close" }).first().click();
  await openOptions();
  await page.getByRole("button", { name: "Audit" }).click();
  const auditDialog = page.getByRole("dialog", { name: "Audit" });
  await expect(auditDialog).toBeVisible();
  await expect(auditDialog.getByText("admin.user.created", { exact: false })).toBeVisible();
  await auditDialog.getByRole("button", { name: "Close" }).click();
  await page.getByRole("button", { name: "Claude Code" }).click();
  const claudeCodeDialog = page.getByRole("dialog", { name: "Claude Code" });
  await expect(claudeCodeDialog).toBeVisible();
  await claudeCodeDialog.getByRole("button", { name: "Close" }).click();
  await page.getByRole("button", { name: "Codex" }).click();
  const codexDialog = page.getByRole("dialog", { name: "Codex" });
  await expect(codexDialog).toBeVisible();
  await codexDialog.getByRole("button", { name: "Close" }).click();
  await openOptions();
  await page.getByRole("button", { name: "Provider Keys" }).click();
  const providerKeysDialog = page.getByRole("dialog", { name: "Provider Keys" });
  await expect(providerKeysDialog).toBeVisible();
  await providerKeysDialog.getByRole("button", { name: "Add Endpoint" }).click();
  await providerKeysDialog.getByLabel("Custom endpoint name 1").fill(customEndpointName);
  await providerKeysDialog.getByLabel("Custom endpoint base URL 1").fill("https://openrouter.ai/api/v1");
  await providerKeysDialog.getByLabel("Custom endpoint model id 1-1").fill("openrouter/sonnet");
  await providerKeysDialog.getByLabel("Custom endpoint model label 1-1").fill("OpenRouter Sonnet");
  await providerKeysDialog.getByRole("button", { name: "Save Provider Keys" }).click();
  await expect(providerKeysDialog.getByText(customEndpointName, { exact: true })).toBeVisible();
  await providerKeysDialog.getByRole("button", { name: "Close" }).first().click();
  await openOptions();
  await page.getByRole("button", { name: "Password" }).click();
  const passwordDialog = page.getByRole("dialog", { name: "Password" });
  await expect(passwordDialog).toBeVisible();
  await passwordDialog.getByLabel("Current password", { exact: true }).fill("demo-pass");
  await passwordDialog.getByLabel("New password", { exact: true }).fill(changedPassword);
  await passwordDialog.getByLabel("Confirm new password", { exact: true }).fill(changedPassword);
  await passwordDialog.getByRole("button", { name: "Change Password" }).click();
  await page.getByRole("button", { name: "Log Out" }).click();
  await expect(page.getByRole("button", { name: "Log In" })).toBeVisible();
  await page.getByLabel("Username").fill("demo");
  await page.getByLabel("Password").fill(changedPassword);
  await page.getByRole("button", { name: "Log In" }).click();
  await expect(page.getByRole("heading", { name: "Workspace" })).toBeVisible();
  await openOptions();
  await page.getByRole("button", { name: "Password" }).click();
  const resetPasswordDialog = page.getByRole("dialog", { name: "Password" });
  await expect(resetPasswordDialog).toBeVisible();
  await resetPasswordDialog.getByLabel("Current password", { exact: true }).fill(changedPassword);
  await resetPasswordDialog.getByLabel("New password", { exact: true }).fill("demo-pass");
  await resetPasswordDialog.getByLabel("Confirm new password", { exact: true }).fill("demo-pass");
  await resetPasswordDialog.getByRole("button", { name: "Change Password" }).click();
  await resetPasswordDialog.getByRole("button", { name: "Close" }).click();
  await openOptions();
  await page.getByRole("button", { name: "Delete Account" }).click();
  const deleteDialog = page.getByRole("dialog", { name: "Delete Account" });
  await expect(deleteDialog).toBeVisible();
  const continueDeleteButton = deleteDialog.getByRole("button", { name: "Continue" });
  await expect(continueDeleteButton).toBeDisabled();
  await deleteDialog.getByLabel("Delete account username confirmation").fill("demo");
  await expect(continueDeleteButton).toBeEnabled();
  const deleteRequestPromise = page.waitForResponse((response) => {
    return response.url().includes("/api/account/delete-request") && response.request().method() === "POST";
  });
  await continueDeleteButton.scrollIntoViewIfNeeded();
  await continueDeleteButton.click({ force: true });
  const deleteRequest = await deleteRequestPromise;
  expect(deleteRequest.status()).toBe(201);
  const deletePayload = await deleteRequest.json();
  const deleteCode = deletePayload.devVerificationCode?.match(/\b(\d{6})\b/)?.[1] ?? deletePayload.devVerificationCode;
  expect(deleteCode).toBeTruthy();
  await deleteDialog.getByLabel("Delete verification code").fill(deleteCode!);
  await deleteDialog.getByRole("button", { name: "Verify delete code" }).click();
  await expect(deleteDialog.getByText("THIS WILL PERMANENTLY DELETE ALL YOUR DATA", { exact: false })).toBeVisible();
  const deleteAccountButton = deleteDialog.getByRole("button", { name: "Delete My Account" });
  await deleteAccountButton.scrollIntoViewIfNeeded();
  await deleteAccountButton.click({ force: true });
  await expect(deleteDialog.getByText("Cannot delete the last admin account")).toBeVisible();
});

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
