import type { ContextSettings, PromptFragment } from "@tracyhill-rp/contracts";

import { buildCharacterIntegrityBlock, buildStyleGateBlock } from "../world/characterIntegrity";
import { buildContentHonestyBlock, buildContentHonestyEscalationBlock, buildIcebreakerTurnHonest, contentHonestyApplies } from "../world/contentHonesty";
import { buildGritBlocks, clampStance, clampTier } from "../world/gritContract";
import { buildSceneTempoBlock, type TempoGear } from "../world/sceneTempo";
import { buildInitiativeNorms, buildPlayerAuthorityReminder, buildWorldAuthorityNorms, renderAntiRepetitionRules, SCENE_BLOCK_REMINDER } from "./chatService";
import { buildKnowledgeEnforcementInstruction, buildSceneTrackingInstruction } from "./sceneParser";
import { TURN_BLOCK_ORDER, turnBlockAllowed, type TurnBlockId } from "./turnBlocks";

/**
 * The Engine dialog's "Injected text" viewer (2026-09-24). One entry per block the chat service wraps around the campaign
 * prompt, in the order the model reads them, built by the SAME functions the live turn calls —
 * so the viewer cannot drift from the wire. `text` is the exact string for the system texts;
 * per-turn content (agendas, attire, contests …) is composed from campaign state and is
 * described instead, with where it is edited. `active` says whether the block is injected for
 * this session's settings and composer.
 */
export interface PromptFragmentInput {
  settings: ContextSettings;
  /** The session's composer model, for the provider-gated content-honesty stack. */
  model: { id: string; provider: string } | null;
  campaignPrompt: string | null;
  antiRepetitionJson: string | null;
}

const SYSTEM = "System prompt — every campaign turn, ahead of the campaign prompt";
const TURN = "Per-turn blocks — appended to your newest message, in this order";
const ROLE = "Assistant role";

export function listPromptFragments(input: PromptFragmentInput): PromptFragment[] {
  const s = input.settings;
  const model = input.model;
  const keys = s.playerCharacterKeys ?? [];
  const stance = clampStance(s.worldStance);
  const tier = clampTier(s.depictionTier);
  const honestyApplies = model ? contentHonestyApplies(model) : false;
  const honestyOn = Boolean(s.contentHonestyEnabled) && honestyApplies;
  const honestyNote = !s.contentHonestyEnabled
    ? "Off: the Content honesty switch is off."
    : !model
      ? "Not injected: the session has no composer model."
      : !honestyApplies
        ? `Not injected on this composer (${model.id}, ${model.provider}): the stack fires only on Google composers and Kimi K3.`
        : null;
  const rules = renderAntiRepetitionRules(input.antiRepetitionJson);
  const campaignPrompt = input.campaignPrompt?.trim() || null;

  const f = (fragment: PromptFragment) => fragment;
  const on = (id: TurnBlockId) => turnBlockAllowed(id, s, model);
  const turnFragments: Record<TurnBlockId, PromptFragment[]> = {
    retrieved_context: [f({ id: "retrieved_context", origin: "Your lorebook entries, chosen each turn by the retrieval passes (keywords, embeddings, HyDE, the researcher).", editing: "Edit the entries in the Lorebook; tune which ones are chosen on the Context page. The Preview chip shows this turn's picks.", settings: ["mode", "embeddingModel", "semanticTopK", "semanticThreshold", "scanDepth", "retrievalBudgetTokens", "threadGuaranteeTokens", "coldInflationWeightMultiplier", "hydeEnabled", "hydeModel", "researcherEnabled", "researcherModel", "researcherMaxPicks"], group: TURN, title: "Retrieved lorebook entries", level: "dynamic", placement: "<retrieved_context> — the first block.", active: on("retrieved_context"), note: on("retrieved_context") ? "Chosen each turn by the retrieval passes; the Preview chip lists this turn's entries. The entries themselves live in the Lorebook." : "Off: retrieval mode is Off.", text: null, editIn: "lorebook" })],
    character_agendas: [f({ id: "character_agendas", origin: "Each present NPC's drive sheet — wants, goals and pressures — written by the drive-sheet worker after settled turns and by you in Drives.", editing: "Edit any character's sheet in Drives; switch the block off with NPC agendas (World page).", settings: ["npcAgendaEnabled"], group: TURN, title: "Character agendas", level: "dynamic", placement: "<character_agendas>", active: on("character_agendas"), note: on("character_agendas") ? "Present NPCs' wants and pressures, read from their drive sheets each turn." : "Off: the NPC agendas switch is off.", text: null, editIn: "drives" })],
    // No dial: the trigger is a comms reference in the last exchange (it
    // used to be linked to NPC agendas, which does not control it).
    absent_contacts: [f({ id: "absent_contacts", origin: "The same drive sheets, when a turn reaches for someone offscreen.", editing: "Edit the sheet in Drives. No switch controls this block.", settings: [], group: TURN, title: "Absent contacts", level: "dynamic", placement: "<absent_contacts> — only when the turn reaches for comms.", active: on("absent_contacts"), note: "Fires only when the last exchange mentions a phone, a text or a message, whatever the dials say; it lists how characters who are not present stand toward the player character.", text: null, editIn: "drives" })],
    offscreen_memory: [f({ id: "offscreen_memory", origin: "World-tick events you applied (Advance the world), written by the world-tick model.", editing: "Review, edit or reject a tick in the World drawer before it applies; Apply ticks automatically skips that review.", settings: ["worldTickModel", "worldTickAutoApply"], group: TURN, title: "Offscreen memory", level: "dynamic", placement: "<offscreen_memory>", active: on("offscreen_memory"), note: "Applied world-tick events the cast would remember.", text: null, editIn: null })],
    clock_pressure: [f({ id: "clock_pressure", origin: "Threat clocks in campaign state, advanced by world ticks at the Threat pacing rate.", editing: "Not hand-edited; change the pace on the World page. Inert below stance 2.", settings: ["storytellerPacing", "worldStance"], group: TURN, title: "Threat clocks", level: "dynamic", placement: "The clock-pressure block.", active: on("clock_pressure"), note: on("clock_pressure") ? "Offscreen threat clocks, advanced by world ticks at the Threat pacing rate." : "Inert below stance 2.", text: null, editIn: null })],
    // Stance 2 and not a Continue, as the live gate.
    contested_outcome: [f({ id: "contested_outcome", origin: "Rolled by the server each turn: a classifier (the World-state model, or the drive model when that is unset) reads your turn, dice decide, and the stance weights the odds.", editing: "Not editable; switch it off with Contested outcomes, or change the odds through World stance. Inert below stance 2.", settings: ["contestedOutcomesEnabled", "worldStance", "worldStateModel"], group: TURN, title: "Contested outcome", level: "dynamic", placement: "Near the end, with the settled facts.", active: on("contested_outcome"), note: !s.contestedOutcomesEnabled ? "Off: the Contested outcomes switch is off." : stance < 2 ? "Inert below stance 2." : "The server's classification and dice result for this turn, told to the model as an outcome to render. A fresh send and a regenerate classify the turn; a Continue carries no new contest.", text: null, editIn: null })],
    // No dial: the ledger renders whenever it holds rows.
    consequences: [f({ id: "consequences", origin: "Campaign state recorded by the world-state model from finished turns: threats, deaths, maimings, grudges (deaths pass an adversarial check first).", editing: "Not hand-edited here. Record world state (World page) stops new entries and is inert below stance 2; entries already recorded keep rendering.", settings: ["worldStateExtractionEnabled", "worldStance", "worldStateModel"], group: TURN, title: "Settled consequences", level: "dynamic", placement: "Near the end so a regeneration cannot walk them back.", active: on("consequences"), note: "Renders whenever the campaign's ledger holds consequences, at any stance and whatever Record world state says; the ledger fills only while Record world state is on at stance 2 or above.", text: null, editIn: null })],
    // Attire tracking alone, as the live gate: the validator only writes new records.
    character_attire: [f({ id: "character_attire", origin: "Recorded by the scene validator after each reply.", editing: "Edit a character's attire from their chip in the cast strip; switch it off with Attire tracking (Scene & craft).", settings: ["attireTrackingEnabled", "attireStaleTurnThreshold", "sceneValidatorEnabled"], group: TURN, title: "Character attire", level: "dynamic", placement: "<character_attire>", active: on("character_attire"), note: !on("character_attire") ? "Off: the Attire tracking switch is off." : s.sceneValidatorEnabled ? "Each present character's recorded attire, reconciled by the scene validator after every reply." : "Each present character's stored attire. The Scene validator is off, so no new records are written and the lines age; an edit from the cast chip still applies.", text: null, editIn: null })],
    // No dial: every due beat fires, whoever armed it.
    due_beats: [f({ id: "due_beats", origin: "Armed by the Dramatist from live threads, beats, concealments and sealed schemes (each beat in the Dramatist model's wording), by a threat clock that fills, or added by hand with the add-beat tool.", editing: "Not hand-edited here; set Intensity and Tick cadence on the World page. Switching the Dramatist off stops new arming; beats already armed still fire.", settings: ["dramatistEnabled", "dramatistIntensity", "tickEveryNthRollingDiff", "dramatistModel"], group: TURN, title: "Due beats", level: "dynamic", placement: "<due_beats>", active: on("due_beats"), note: s.dramatistEnabled ? "Beats that are now due, whoever armed them: the Dramatist, a filled threat clock or a hand-added beat." : "Beats that come due still fire with the Dramatist off (armed by a filled threat clock or added by hand); the switch only stops the Dramatist arming new ones.", text: null, editIn: null })],
    antagonist_intent: [f({ id: "antagonist_intent", origin: "Authored each turn by the antagonist model before the reply renders.", editing: "Not editable; choose the model, or set it to Off so the render model decides (World page).", settings: ["antagonistModel"], group: TURN, title: "Antagonist intent", level: "dynamic", placement: "Just ahead of any spotlight — a settled decision the turn must carry out.", active: on("antagonist_intent"), note: on("antagonist_intent") ? `Authored by ${s.antagonistModel} on a fresh user turn when an antagonist (a sealed drive sheet or an active scheme) is on stage; a regenerate or continue carries no new intent.` : "Off: no antagonist model is set, so the render model decides.", text: null, editIn: null })],
    scene_tempo: (["NEUTRAL", "STEADY", "DRIVE"] as TempoGear[]).map((gear) => f({ id: `scene_tempo_${gear.toLowerCase()}`, origin: "Built into TracyHill RP; one of three fixed texts, rolled per user message.", editing: "Read-only. Switch it off with Scene tempo (Scene & craft); the gear a turn rolled shows in Preview.", settings: ["sceneTempoEnabled"], group: TURN, title: `Scene tempo — ${gear}`, level: "system", placement: "After the settled facts, before the spotlight. One gear is rolled per user message (neutral 40% / steady 40% / drive 20%, stepped up after a quiet streak; a turn carrying settled work is floored to STEADY).", active: on("scene_tempo"), note: on("scene_tempo") ? null : "Off: the Scene tempo switch is off.", text: buildSceneTempoBlock(gear), editIn: null })),
    spotlight: [f({ id: "spotlight", origin: "Set by you from the composer's spotlight menu (character + steer).", editing: "Change or clear it from the same menu.", settings: [], group: TURN, title: "Spotlight", level: "dynamic", placement: "Closest to the beat the model writes.", active: on("spotlight"), note: "Set when you put a character in the spotlight from the cast chip.", text: null, editIn: null })],
    style_gate: [f({ id: "style_gate", origin: "Built into TracyHill RP (the Character Engine); the same text for every campaign.", editing: "Read-only; it rides with the Character voice pack switch (Scene & craft).", settings: ["characterIntegrityEnabled"], group: TURN, title: "Style gate", level: "system", placement: "Second to last — only the player-authority reminder follows.", active: on("style_gate"), note: on("style_gate") ? null : "Off: the Character voice pack switch is off.", text: buildStyleGateBlock(), editIn: null })],
    content_honesty_escalation: [f({ id: "content_honesty_escalation", origin: "Built into TracyHill RP (the refusal-prevention stack, 2026-08-30); the same text for every campaign. It fires only on Google composers and Kimi K3.", editing: "Read-only. Switch it off with Content honesty (Scene & craft).", settings: ["contentHonestyEnabled"], group: TURN, title: "Content honesty — scope confirmation", level: "system", placement: "Between the style gate and the player-authority reminder.", active: on("content_honesty_escalation"), note: honestyNote, text: buildContentHonestyEscalationBlock(), editIn: null })],
    player_authority: [f({ id: "player_authority", origin: "Built into TracyHill RP; the names come from Player character names.", editing: "Set the names on the World page (none = not injected); the wording is fixed.", settings: ["playerCharacterKeys"], group: TURN, title: "Player-authority reminder", level: "system", placement: "The absolute last line before your turn.", active: on("player_authority"), note: keys.length ? null : "Not injected: no player character names are set (World page).", text: buildPlayerAuthorityReminder(keys.length ? keys : ["‹player character names›"]), editIn: null })],
  };
  return [
    // ── system prompt, in section order (chatService.buildSessionSystemPrompt) ──
    f({ id: "scene_tracking", origin: "Built into TracyHill RP; the same text for every campaign.", editing: "Not editable and always on: it is the infrastructure that reads the [SCENE] block off every reply.", settings: [], group: SYSTEM, title: "Scene tracking instruction", level: "system", placement: "First section.", active: true, note: "Always on for campaign sessions.", text: buildSceneTrackingInstruction(), editIn: null }),
    f({ id: "world_authority", origin: "Built into TracyHill RP; it takes the player character names from this session's settings.", editing: "The names are yours (Player character names, World page); the wording is fixed and always on.", settings: ["playerCharacterKeys"], group: SYSTEM, title: "World authority norms", level: "system", placement: "Second section.", active: true, note: keys.length ? `Names the player's character: ${keys.join(" / ")}.` : "Always on; no player character names are set, so the norms carry no name.", text: buildWorldAuthorityNorms(keys), editIn: null }),
    f({ id: "knowledge_enforcement", origin: "Built into TracyHill RP; the same text for every campaign.", editing: "Not editable; always on for campaign sessions.", settings: [], group: SYSTEM, title: "Knowledge enforcement", level: "system", placement: "Third section.", active: true, note: "Always on for campaign sessions.", text: buildKnowledgeEnforcementInstruction(), editIn: null }),
    f({ id: "initiative_norms", origin: "Built into TracyHill RP; one of three fixed texts chosen by the NPC initiative dial.", editing: "Pick Subtle, Normal or Assertive on the World page; the wording itself is fixed.", settings: ["npcInitiative"], group: SYSTEM, title: `NPC initiative norms — ${s.npcInitiative}`, level: "system", placement: "After the scene instruction; runtime-injected so the system-prompt audit worker can never rewrite it.", active: true, note: null, text: buildInitiativeNorms(s.npcInitiative), editIn: null }),
    f({ id: "grit_floor", origin: "Built into TracyHill RP (the adversarial-world contract); assembled from the World stance and Depiction tier dials.", editing: "Move the two dials on the World page and the block changes; the clauses themselves are fixed.", settings: ["worldStance", "depictionTier"], group: SYSTEM, title: `World floor rules — stance ${stance}, depiction tier ${tier}`, level: "system", placement: "After the norms so it wins on recency. The craft and physics blocks fire at every stance; friction and decentring join at stance 2, harm, permanence, threat follow-through and antagonist integrity at 3, convergence at 4; depiction clauses accumulate with the tier (tier 0 injects none).", active: true, note: null, text: buildGritBlocks(s), editIn: null }),
    f({ id: "voice_pack", origin: "Built into TracyHill RP (the Character Engine); the same text for every campaign.", editing: "Read-only. Switch it off with Character voice pack (Scene & craft). Voice detail for one character belongs in that character's lorebook entry or drive sheet, which the model reads alongside this.", settings: ["characterIntegrityEnabled"], group: SYSTEM, title: "Character voice pack", level: "system", placement: "After the floor rules; the campaign prompt below still owns tone and setting.", active: Boolean(s.characterIntegrityEnabled), note: s.characterIntegrityEnabled ? null : "Off: the Character voice pack switch is off.", text: buildCharacterIntegrityBlock(), editIn: null }),
    f({ id: "content_honesty_section", origin: "Built into TracyHill RP (the refusal-prevention stack, 2026-08-30); the same text for every campaign. It fires only on Google composers and Kimi K3.", editing: "Read-only. Switch it off with Content honesty (Scene & craft).", settings: ["contentHonestyEnabled"], group: SYSTEM, title: "Content honesty — consent and scope section", level: "system", placement: "Last runtime-injected section before the campaign prompt.", active: honestyOn, note: honestyNote, text: buildContentHonestyBlock(), editIn: null }),
    f({ id: "campaign_prompt", origin: "Written when the campaign was created — by you, or by the campaign wizard from your answers — and every time you edit it since.", editing: "Fully yours: Campaigns panel → the prompt editor. The system-prompt audit worker may also rewrite it (an adversarial reviewer must accept the rewrite first); every version is kept and can be restored in Campaigns.", settings: [], group: SYSTEM, title: "Campaign prompt", level: "campaign", placement: "The campaign's own system prompt; the cached block starts here.", active: Boolean(campaignPrompt), note: campaignPrompt ? "Yours to edit in the Campaigns panel." : "This campaign has no prompt yet — write one in the Campaigns panel.", text: campaignPrompt, editIn: "campaign" }),
    f({ id: "anti_repetition_rules", origin: "Written by the repetition worker from this campaign's transcript; each rule's wording is the worker's. Campaign state, shared by every session in the campaign.", editing: "Not hand-edited. The Workers page caps how many rules apply (Maximum rules) and retires unmatched ones (Retire rules after); the master switch stops new ones.", settings: ["maxAntiRepetitionRules", "antiRepArchiveAfter"], group: SYSTEM, title: "Anti-repetition rules", level: "campaign", placement: "After the campaign prompt, inside the cached block.", active: Boolean(rules), note: rules ? "Written by the repetition worker from this campaign's transcript; the Workers page caps and retires them." : "No rules yet — the repetition worker writes them as the transcript grows.", text: rules, editIn: null }),
    f({ id: "scene_block_reminder", origin: "Built into TracyHill RP; the same text for every campaign.", editing: "Not editable; always on for campaign sessions.", settings: [], group: SYSTEM, title: "[SCENE] block reminder", level: "system", placement: "Last line of the system prompt, except on a turn that carries a one-shot ## SCENE CORRECTION (your corrected scene for the reply being rewritten), which is appended after it for that one call and never kept.", active: true, note: "Always on for campaign sessions.", text: SCENE_BLOCK_REMINDER, editIn: null }),

    // ── per-turn blocks, in wire order: TURN_BLOCK_ORDER (turnBlocks.ts) is the list
    //    chatService builds `parts` from, and every "active" flag below is the same
    //    gate the live turn asks ──
    ...TURN_BLOCK_ORDER.flatMap((id) => turnFragments[id]),

    // ── assistant role ──
    f({ id: "content_honesty_icebreaker", origin: "Built into TracyHill RP (the refusal-prevention stack, 2026-08-30); the same text for every campaign. It fires only on Google composers and Kimi K3.", editing: "Read-only. Switch it off with Content honesty (Scene & craft).", settings: ["contentHonestyEnabled"], group: ROLE, title: "Content honesty — icebreaker", level: "system", placement: "Prepended to the first assistant reply, so the model reads its own prior agreement.", active: honestyOn, note: honestyNote, text: buildIcebreakerTurnHonest(), editIn: null }),
  ];
}
