-- 2026-10-01 model refresh: retarget the ids the catalog removed to their successors.
--   kimi-k2.6-fireworks              -> kimi-k2.6                 (Fireworks took K2.6 off serverless 2026-09-25; every request 404s)
--   deepseek-v4-flash                -> deepseek-flash            (DeepSeek retired V4 Flash; the new id is V4.1 Flash)
--   mimo-v2.5-pro                    -> mimo-v2.6-pro             (Xiaomi shuts V2.5 down 2026-10-21, no replacement routing)
--   mimo-v2.5                        -> mimo-v2.6-flash           (same; V2.6 Flash is V2.5's price point)
--   gpt-5.3-codex-spark-codex-bridge -> gpt-6-luna-codex-bridge   (Codex retired Spark 2026-09-14)
--   gpt-5.5-codex-bridge             -> gpt-6.1-sol-codex-bridge  (GPT-5.5 leaves Codex 2026-10-14)
-- Measured before writing (a copy of a live database, 2026-10-01): no session, pending
-- reply, wizard run, session dial or pipeline run references any of them; only 22
-- historical messages do, and messages keep their original model_id on purpose
-- (0060/0073/0080 pattern). So this is the safety net for anything written between
-- the measurement and the deploy. Every statement is idempotent (`WHERE … IN (…)`).
-- Key lists: the sessions' Engine model dials (packages/contracts context.ts, minus
-- embeddingModel) and every model key the run-details writers store
-- (pipelineQueueService + pipelineService recapModel; 0082/0087's lesson).

UPDATE sessions SET model_id = CASE model_id WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' ELSE model_id END
WHERE model_id IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pending_assistant_messages SET model_id = CASE model_id WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' ELSE model_id END
WHERE model_id IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE wizard_runs SET model_id = CASE model_id WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' ELSE model_id END
WHERE model_id IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.antagonistModel', CASE json_extract(context_overrides_json, '$.antagonistModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.antagonistModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.auditModel', CASE json_extract(context_overrides_json, '$.auditModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.auditModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.dramatistModel', CASE json_extract(context_overrides_json, '$.dramatistModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.dramatistModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.driveModel', CASE json_extract(context_overrides_json, '$.driveModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.driveModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.hydeModel', CASE json_extract(context_overrides_json, '$.hydeModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.hydeModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.repetitionModel', CASE json_extract(context_overrides_json, '$.repetitionModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.repetitionModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.researcherModel', CASE json_extract(context_overrides_json, '$.researcherModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.researcherModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.rollingModel', CASE json_extract(context_overrides_json, '$.rollingModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.rollingModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.sceneValidatorModel', CASE json_extract(context_overrides_json, '$.sceneValidatorModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.sceneValidatorModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.syspromptAuditModel', CASE json_extract(context_overrides_json, '$.syspromptAuditModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.syspromptAuditModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.worldStateModel', CASE json_extract(context_overrides_json, '$.worldStateModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.worldStateModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE sessions SET context_overrides_json = json_set(context_overrides_json, '$.worldTickModel', CASE json_extract(context_overrides_json, '$.worldTickModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE context_overrides_json IS NOT NULL AND json_valid(context_overrides_json) AND json_extract(context_overrides_json, '$.worldTickModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pipeline_runs SET details_json = json_set(details_json, '$.rollingModel', CASE json_extract(details_json, '$.rollingModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE details_json IS NOT NULL AND json_valid(details_json) AND json_extract(details_json, '$.rollingModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pipeline_runs SET details_json = json_set(details_json, '$.consolidationModel', CASE json_extract(details_json, '$.consolidationModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE details_json IS NOT NULL AND json_valid(details_json) AND json_extract(details_json, '$.consolidationModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pipeline_runs SET details_json = json_set(details_json, '$.archivalModel', CASE json_extract(details_json, '$.archivalModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE details_json IS NOT NULL AND json_valid(details_json) AND json_extract(details_json, '$.archivalModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pipeline_runs SET details_json = json_set(details_json, '$.trackerModel', CASE json_extract(details_json, '$.trackerModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE details_json IS NOT NULL AND json_valid(details_json) AND json_extract(details_json, '$.trackerModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pipeline_runs SET details_json = json_set(details_json, '$.repetitionModel', CASE json_extract(details_json, '$.repetitionModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE details_json IS NOT NULL AND json_valid(details_json) AND json_extract(details_json, '$.repetitionModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pipeline_runs SET details_json = json_set(details_json, '$.auditModel', CASE json_extract(details_json, '$.auditModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE details_json IS NOT NULL AND json_valid(details_json) AND json_extract(details_json, '$.auditModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pipeline_runs SET details_json = json_set(details_json, '$.syspromptAuditModel', CASE json_extract(details_json, '$.syspromptAuditModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE details_json IS NOT NULL AND json_valid(details_json) AND json_extract(details_json, '$.syspromptAuditModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pipeline_runs SET details_json = json_set(details_json, '$.driveModel', CASE json_extract(details_json, '$.driveModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE details_json IS NOT NULL AND json_valid(details_json) AND json_extract(details_json, '$.driveModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pipeline_runs SET details_json = json_set(details_json, '$.worldTickModel', CASE json_extract(details_json, '$.worldTickModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE details_json IS NOT NULL AND json_valid(details_json) AND json_extract(details_json, '$.worldTickModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pipeline_runs SET details_json = json_set(details_json, '$.dramatistModel', CASE json_extract(details_json, '$.dramatistModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE details_json IS NOT NULL AND json_valid(details_json) AND json_extract(details_json, '$.dramatistModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');

UPDATE pipeline_runs SET details_json = json_set(details_json, '$.recapModel', CASE json_extract(details_json, '$.recapModel') WHEN 'kimi-k2.6-fireworks' THEN 'kimi-k2.6' WHEN 'deepseek-v4-flash' THEN 'deepseek-flash' WHEN 'mimo-v2.5-pro' THEN 'mimo-v2.6-pro' WHEN 'mimo-v2.5' THEN 'mimo-v2.6-flash' WHEN 'gpt-5.3-codex-spark-codex-bridge' THEN 'gpt-6-luna-codex-bridge' WHEN 'gpt-5.5-codex-bridge' THEN 'gpt-6.1-sol-codex-bridge' END)
WHERE details_json IS NOT NULL AND json_valid(details_json) AND json_extract(details_json, '$.recapModel') IN ('kimi-k2.6-fireworks','deepseek-v4-flash','mimo-v2.5-pro','mimo-v2.5','gpt-5.3-codex-spark-codex-bridge','gpt-5.5-codex-bridge');
